### ISSUE TITLE
Script doesn't work at all

### ISSUE THREAD

**Issue by AndrewRest** [alekssakovsky/pdf-digital-signature#6]
[info] [phantom] Done 8 steps in 45053ms

Warning! I can't merge PDF files:
"field-keywords" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.

"field-keywords" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.

[info] [phantom] Starting...
[info] [phantom] Running suite: 8 steps
[info] [phantom] Step anonymous 3/8 https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-videoundefined (HTTP 404)
[info] [phantom] Capture saved to C:/Users/acer/Documents/GitHub/pdf-digital-signature/temp/undefined 1.pdf

**Comment by alekssakovsky** [comment]
fixed
