### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by AndrewRest** [alekssakovsky/pdf-digital-signature#9]
Especially interesting log https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-video**undefined**

Full log:
C:\Users\acer\Documents\GitHub\pdf-digital-signature>node application.js
2018-10-08T17:45:00.010Z
Go to link: https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Dinstant-video&field-keywords=Stallone
Go to link: https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Dinstant-video&field-keywords=Arnold
Warning! Can't merge PDF files:
"field-keywords" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.

"field-keywords" ?? ????? ???????? ??? ?????
????????, ??????? ?????? ??? ?????? ????.

[info] [phantom] Starting...
[info] [phantom] Running suite: 8 steps
[info] [phantom] Step anonymous 3/8 https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-videoundefined (HTTP 404)
[info] [phantom] Capture saved to C:/Users/acer/Documents/GitHub/pdf-digital-signature/temp/undefined 1.pdf
[info] [phantom] Step anonymous 3/8: done in 15112ms.
[info] [phantom] Step anonymous 4/8 https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-videoundefined (HTTP 404)
[info] [phantom] Step anonymous 4/8: done in 20044ms.
[info] [phantom] Step anonymous 5/8 https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-videoundefined (HTTP 404)
[info] [phantom] Capture saved to C:/Users/acer/Documents/GitHub/pdf-digital-signature/temp/undefined 2.pdf
[info] [phantom] Step anonymous 5/8: done in 25098ms.
[info] [phantom] Step anonymous 6/8 https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-videoundefined (HTTP 404)
[info] [phantom] Step anonymous 6/8: done in 30046ms.
[info] [phantom] Step anonymous 7/8 https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-videoundefined (HTTP 404)
[info] [phantom] Capture saved to C:/Users/acer/Documents/GitHub/pdf-digital-signature/temp/undefined 3.pdf
[info] [phantom] Step anonymous 7/8: done in 35086ms.
[info] [phantom] Step anonymous 8/8 https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias=instant-videoundefined (HTTP 404)
[info] [phantom] Step anonymous 8/8: done in 40054ms.
[info] [phantom] Done 8 steps in 45056ms

**Comment by alekssakovsky** [comment]
fixed
